### ISSUE TITLE
Make it possible to configure and start seastar from Rust

### ISSUE THREAD

**Issue by piodul** [zpp-2022-rust-seastar/seastar-rs#1]
We would like to allow Rust to start the Seastar runtime.

In C++, the process of starting the runtime has a small number of steps:

- First, `app_template::seastar_options` is created and set appropriately
- The `app_template` is created, with seastar options passed as the first argument
- Finally, `app_template::run` is called to start the application

We would like to offer a similar experience in Rust:

- `Options`: for now let's only make it possible to set the application name, description and the number of shards. The properties should be settable via setters/getters.
- `AppTemplate`: it should be possible to create it from `Options` and it should have only one method `run` which works analogously as the original `app_template::run`.

**Comment by kfernandez31** [comment]
I can't edit assignees, so I hope this comment suffices - I'm assigning myself.

**Comment by piodul** [comment]
Fixed in https://github.com/zpp-2022-rust-seastar/seastar-rs/pull/23 .
