### ISSUE TITLE
Ensure API safety when running code without having a runtime started

### ISSUE THREAD

**Issue by cvybhu** [zpp-2022-rust-seastar/seastar-rs#13]
We are aiming to make our API safe, which means that no matter what Rust code the user writes the program won't encounter any memory problems or undefined behavior.

When running seastar functions we should make sure that a runtime has been started. Without a runtime we might get a segfault, which isn't considered safe.

When a runtime isn't started we can just panic, that's what tokio does.

**Comment by piodul** [comment]
Done in: https://github.com/zpp-2022-rust-seastar/seastar-rs/pull/27
